import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const jetBrains_Mono = JetBrains_Mono({
  variable: "--font-jetBrains",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${jetBrains_Mono.variable} h-full antialiased scroll-smooth`}>
    <body>
      <div className="fixed inset-0 bg-[#0C0C14]">
        <div className="absolute top-[8%] left-[10%] w-[20vw] h-[11vw] bg-purple-300/10 rounded-full blur-[22px]" />
        <div className="absolute top-[14%] left-[18%] w-[14vw] h-[8vw] bg-purple-200/5 rounded-full blur-[16px]" />
        <div className="absolute top-[6%] left-[28%] w-[18vw] h-[10vw] bg-purple-200/10 rounded-full blur-[24px]" />
        <div className="absolute bottom-[30%] left-[70%] w-[22vw] h-[12vw] bg-indigo-300/10 rounded-full blur-[25px]" />
        <div className="absolute bottom-[20%] left-[55%] w-[14vw] h-[12vw] bg-indigo-200/5 rounded-full blur-[25px]" />
        <div className="absolute bottom-[20%] right-[15%] w-[20vw] h-[11vw] bg-indigo-200/10 rounded-full blur-[15px]" />
        <div className="absolute backdrop-blur-2xl" />
      </div>
      <div className="relative w-full">
        <Header />
        {children}
      </div>
    </body>
    </html>
  );
}
